server:
  thanos:
    create: true
    resources:
       requests:
         cpu: 2
         memory: 512Mi
       limits:
         cpu: 3
         memory: 1024Mi
prometheus:
  serviceMonitorNamespaceSelector:
    matchLabels:
      helm-monitoring: prometheus
